services:

  redis:
    image: redis:latest
    container_name: redis_distributed
    env_file: 'docker.env'
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 30 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - data-volume:/data

  _build:
    image: ubuntu-python-redis
    pull_policy: never
    command: ['echo', 'build completed']
    build: 
      context: .
      dockerfile: dockerfile

  monitor:
    image: ubuntu-python-redis
    pull_policy: never
    depends_on:
      - _build
    env_file: 'docker.env'
    command: >
      sh -c "python3 /sgx/manager/workers/manager.py &
             flask --app /sgx/manager/workers/api.py run --host=0.0.0.0"
    ports:
      - "8001:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  data-volume: