services:

  _build:
    image: ubuntu-python-monitor
    pull_policy: never
    command: ['echo', 'build completed']
    build: 
      context: .
      dockerfile: dockerfile
      no_cache: true

  monitor:
    image: ubuntu-python-monitor
    pull_policy: never
    depends_on:
      - _build
    env_file: '.env'
    command: >
      sh -c "python3 /sgx/monitor/workers/agent.py &
             flask --app /sgx/monitor/workers/api.py run --host=0.0.0.0"
    pid: "host"
    ports:
      - "8000:5000"