FROM ubuntu
COPY requirements.txt /sgx/monitor/requirements.txt

RUN apt-get update
RUN apt-get -y install curl

RUN apt-get -y install python3
RUN apt install -y python3-pip

RUN cd /sgx/monitor
RUN pip3 install -r /sgx/monitor/requirements.txt --break-system-packages

COPY . /sgx/monitor
EXPOSE 5000